export const APPEAL_TYPE_PREFIX = {
    other: 'А',
    work: 'Б',
    benefits: 'В',
    pension: 'Г',
    payments: 'Д',
    homeCare: 'Е',
    elderlySupport: 'Ё',
    disabilityAid: 'Ж',
    housing: 'З',
    childSupport: 'И',
    legalHelp: 'Ё',
    consultation: 'К',
    transportBenefit: 'Л',
    documents: 'М',
    crisisSupport: 'Н',
    daycare: 'О',
    socialCard: 'П',
    utilityDiscount: 'Р',
};